using IplMerchStore.Application.Common;
using IplMerchStore.Application.DTOs;
using IplMerchStore.Application.Interfaces;
using IplMerchStore.Application.Validators;
using IplMerchStore.Domain.Entities;
using IplMerchStore.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IplMerchStore.Infrastructure.Services;

/// <summary>
/// Service for managing franchises
/// </summary>
public class FranchiseService : IFranchiseService
{
    private readonly AppDbContext _dbContext;
    private readonly ILogger<FranchiseService> _logger;

    public FranchiseService(AppDbContext dbContext, ILogger<FranchiseService> logger)
    {
        _dbContext = dbContext;
        _logger = logger;
    }

    public async Task<Result<PagedResult<FranchiseDto>>> GetAllFranchisesAsync(int pageNumber = 1, int pageSize = 10, CancellationToken cancellationToken = default)
    {
        try
        {
            var query = _dbContext.Franchises.AsQueryable();
            var totalCount = await query.CountAsync(cancellationToken);

            var franchises = await query
                .OrderBy(f => f.Name)
                .Skip((pageNumber - 1) * pageSize)
                .Take(pageSize)
                .Select(f => new FranchiseDto
                {
                    Id = f.Id,
                    Name = f.Name,
                    ShortCode = f.ShortCode,
                    PrimaryColor = f.PrimaryColor,
                    SecondaryColor = f.SecondaryColor,
                    LogoUrl = f.LogoUrl,
                    CreatedAtUtc = f.CreatedAtUtc,
                    UpdatedAtUtc = f.UpdatedAtUtc
                })
                .ToListAsync(cancellationToken);

            var pagedResult = new PagedResult<FranchiseDto>(franchises, pageNumber, pageSize, totalCount);
            return Result<PagedResult<FranchiseDto>>.SuccessResult(pagedResult, "Franchises retrieved successfully");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error retrieving franchises");
            return Result<PagedResult<FranchiseDto>>.FailureResult("Failed to retrieve franchises");
        }
    }

    public async Task<Result<FranchiseDto?>> GetFranchiseByIdAsync(int id, CancellationToken cancellationToken = default)
    {
        try
        {
            var franchise = await _dbContext.Franchises
                .Where(f => f.Id == id)
                .Select(f => new FranchiseDto
                {
                    Id = f.Id,
                    Name = f.Name,
                    ShortCode = f.ShortCode,
                    PrimaryColor = f.PrimaryColor,
                    SecondaryColor = f.SecondaryColor,
                    LogoUrl = f.LogoUrl,
                    CreatedAtUtc = f.CreatedAtUtc,
                    UpdatedAtUtc = f.UpdatedAtUtc
                })
                .FirstOrDefaultAsync(cancellationToken);

            if (franchise == null)
            {
                return Result<FranchiseDto?>.FailureResult($"Franchise with ID {id} not found");
            }

            return Result<FranchiseDto?>.SuccessResult(franchise, "Franchise retrieved successfully");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error retrieving franchise with ID {FranchiseId}", id);
            return Result<FranchiseDto?>.FailureResult("Failed to retrieve franchise");
        }
    }

    public async Task<Result<FranchiseDto>> CreateFranchiseAsync(FranchiseInputDto inputDto, CancellationToken cancellationToken = default)
    {
        try
        {
            // Validate input
            var (isValid, validationErrors) = FranchiseValidator.ValidateFranchiseInputDto(inputDto);
            if (!isValid)
            {
                return Result<FranchiseDto>.FailureResult("Validation failed", validationErrors);
            }

            // Check for duplicate name
            var nameExists = await _dbContext.Franchises
                .AnyAsync(f => f.Name.ToLower() == inputDto.Name.ToLower(), cancellationToken);
            if (nameExists)
            {
                return Result<FranchiseDto>.FailureResult("Validation failed", new[] { "Franchise name already exists" });
            }

            // Check for duplicate short code
            var shortCodeExists = await _dbContext.Franchises
                .AnyAsync(f => f.ShortCode.ToLower() == inputDto.ShortCode.ToLower(), cancellationToken);
            if (shortCodeExists)
            {
                return Result<FranchiseDto>.FailureResult("Validation failed", new[] { "Short code already exists" });
            }

            var now = DateTime.UtcNow;
            var franchise = new Franchise
            {
                Id = 0, // Will be generated by database
                Name = inputDto.Name,
                ShortCode = inputDto.ShortCode.ToUpperInvariant(),
                PrimaryColor = inputDto.PrimaryColor,
                SecondaryColor = inputDto.SecondaryColor,
                LogoUrl = inputDto.LogoUrl,
                CreatedAtUtc = now,
                UpdatedAtUtc = now
            };

            _dbContext.Franchises.Add(franchise);
            await _dbContext.SaveChangesAsync(cancellationToken);

            var franchiseDto = new FranchiseDto
            {
                Id = franchise.Id,
                Name = franchise.Name,
                ShortCode = franchise.ShortCode,
                PrimaryColor = franchise.PrimaryColor,
                SecondaryColor = franchise.SecondaryColor,
                LogoUrl = franchise.LogoUrl,
                CreatedAtUtc = franchise.CreatedAtUtc,
                UpdatedAtUtc = franchise.UpdatedAtUtc
            };

            return Result<FranchiseDto>.SuccessResult(franchiseDto, "Franchise created successfully");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating franchise");
            return Result<FranchiseDto>.FailureResult("Failed to create franchise");
        }
    }

    public async Task<Result<FranchiseDto>> UpdateFranchiseAsync(int id, FranchiseInputDto inputDto, CancellationToken cancellationToken = default)
    {
        try
        {
            // Validate input
            var (isValid, validationErrors) = FranchiseValidator.ValidateFranchiseInputDto(inputDto);
            if (!isValid)
            {
                return Result<FranchiseDto>.FailureResult("Validation failed", validationErrors);
            }

            var franchise = await _dbContext.Franchises.FindAsync(new object[] { id }, cancellationToken);
            if (franchise == null)
            {
                return Result<FranchiseDto>.FailureResult($"Franchise with ID {id} not found");
            }

            // Check for duplicate name (excluding current franchise)
            var nameExists = await _dbContext.Franchises
                .AnyAsync(f => f.Name.ToLower() == inputDto.Name.ToLower() && f.Id != id, cancellationToken);
            if (nameExists)
            {
                return Result<FranchiseDto>.FailureResult("Validation failed", new[] { "Franchise name already exists" });
            }

            // Check for duplicate short code (excluding current franchise)
            var shortCodeExists = await _dbContext.Franchises
                .AnyAsync(f => f.ShortCode.ToLower() == inputDto.ShortCode.ToLower() && f.Id != id, cancellationToken);
            if (shortCodeExists)
            {
                return Result<FranchiseDto>.FailureResult("Validation failed", new[] { "Short code already exists" });
            }

            franchise.Name = inputDto.Name;
            franchise.ShortCode = inputDto.ShortCode.ToUpperInvariant();
            franchise.PrimaryColor = inputDto.PrimaryColor;
            franchise.SecondaryColor = inputDto.SecondaryColor;
            franchise.LogoUrl = inputDto.LogoUrl;
            franchise.UpdatedAtUtc = DateTime.UtcNow;

            _dbContext.Franchises.Update(franchise);
            await _dbContext.SaveChangesAsync(cancellationToken);

            var franchiseDto = new FranchiseDto
            {
                Id = franchise.Id,
                Name = franchise.Name,
                ShortCode = franchise.ShortCode,
                PrimaryColor = franchise.PrimaryColor,
                SecondaryColor = franchise.SecondaryColor,
                LogoUrl = franchise.LogoUrl,
                CreatedAtUtc = franchise.CreatedAtUtc,
                UpdatedAtUtc = franchise.UpdatedAtUtc
            };

            return Result<FranchiseDto>.SuccessResult(franchiseDto, "Franchise updated successfully");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error updating franchise with ID {FranchiseId}", id);
            return Result<FranchiseDto>.FailureResult("Failed to update franchise");
        }
    }

    public async Task<Result> DeleteFranchiseAsync(int id, CancellationToken cancellationToken = default)
    {
        try
        {
            var franchise = await _dbContext.Franchises
                .Include(f => f.Products)
                .FirstOrDefaultAsync(f => f.Id == id, cancellationToken);

            if (franchise == null)
            {
                return Result.FailureResult($"Franchise with ID {id} not found");
            }

            // Check if franchise has any products
            if (franchise.Products.Any())
            {
                return Result.FailureResult("Cannot delete franchise that has associated products");
            }

            _dbContext.Franchises.Remove(franchise);
            await _dbContext.SaveChangesAsync(cancellationToken);

            return Result.SuccessResult("Franchise deleted successfully");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error deleting franchise with ID {FranchiseId}", id);
            return Result.FailureResult("Failed to delete franchise");
        }
    }
}
